# Configurações de Conexão com o Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5432/tracker_db
spring.datasource.username=admin
spring.datasource.password=adminpassword

# Configurações do Hibernate/JPA (Faz a ponte entre o Java e o Banco)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true